### PR TITLE
feat: pass through social actions to loginModal

### PR DESCRIPTION
**Pull request by nickfranciosi**
BREAKING CHANGE: this addition breaks the older implemention of having the links live inside the component

### CODE REVIEW

**Comment by thomasthesecond** [comment]
Are you thinking of bumping to version 5.0? I had a list of breaking changes I wanted to merge all at once here, but not sure how reasonable it would be to get them all complete in a timely manor.

https://github.com/lonelyplanet/backpack-ui/milestone/2

**Comment by nickfranciosi** [comment]
@thomasthesecond technically we would for this, but I don't think anything is consuming this component, but if you have other things to add. I am not in a hurry to have it live, I can work with it locally

**Comment by thomasthesecond** [comment]
Ok cool. Most of those changes I want to make are pretty small. The button refactor will have the largest effort, but I'm actually almost done with that. So maybe we can make a breaking change release today or tomorrow?

**Comment by thomasthesecond** [comment]
Also I think for standard-version to pick this up as a breaking change, you would replace `feat:` with `BREAKING CHANGE:` in the subject line.

`BREAKING CHANGE: pass through social actions to loginModal`

**Comment by thomasthesecond** [comment]
We might not need this update any more. The components in https://github.com/lonelyplanet/backpack-ui/pull/322 will eventually deprecate the `ModalContentSocialAuth` component.

**Pull request closed without merging**
