### PR TITLE
update tabbedNav to have no outline on the buttons

### PR DESCRIPTION
**Pull request by katelynp43**
Remove blue outline on tabbedNav button links

### CODE REVIEW

**Comment by thomasthesecond** [comment]
Was this a request from designers? They're killing me with these requests to remove accessibility features from our UI.

**Comment by katelynp43** [comment]
No, it wasn't from designers. I noticed it when I was working on the blog yesterday and prefer to have it removed. :)

**Comment by thomasthesecond** [comment]
Then I'd recommend keeping it or using our gray dotted outline style found in utils/mixins.js. We'll be working on a better style for focus states soon hopefully.

**Comment by katelynp43** [comment]
Hey @thomasthesecond, I think it would look best to remove it, since it doesn't act like a true button. When the outline is there, you loose the red underline that is on the active state. I don't think we need the accessibility outline or a gray dotted line like you previously suggested.  I am attaching a screenshot here so you can see what I am referring too. Do you have further thoughts after seeing this? screen shot 2018-03-08 at 1 10 07 pm

**Comment by thomasthesecond** [comment]
The outline is useful for users who may use their keyboard to navigate the page. Unfortunately, browsers apply the focus state when clicked with a mouse; typically we don't want the outline for mouse users. However, it's useful for keyboard users so we keep it.

Here's a video where I navigate the buttons with my tab key and press enter to "click" on the button

https://cl.ly/323S2K3X1W3G

It's very hard to do this when then outline is removed because you don't know where you are or which button has focus.

If you don't like how the blue outline looks, I recommend using our gray dotted outline or changing the color of the text when focused.

**Comment by thomasthesecond** [comment]
Also, not to :trollface: but http://www.outlinenone.com/ explains the importance of the outline.

**Comment by katelynp43** [comment]
@thomasthesecond that is a great point of view! I appreciate you taking the time to explain this. I hadn't thought about it like that before. Thanks for sharing. I will delete this branch and PR and leave the outline as is. :)

**Pull request closed without merging**
